#!/usr/bin/env python3
"""Run the complete LOS repository or presenter-readiness verification matrix."""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile
from dataclasses import dataclass
from datetime import UTC, date, datetime
from pathlib import Path
from typing import Callable

# Load the sibling BCL module whether run as a script or imported via importlib.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import bcl  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
REACT = ROOT / "los-salesforce-project" / "force-app" / "main" / "default" / "uiBundles" / "losreactapp"
MARKDOWN_LINK = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
# Excluded for the same reason as node_modules: the secret scan governs code we write,
# and minified third-party output produces false positives.
EXCLUDED_PARTS = {
    ".git", "node_modules", "dist", "build", "coverage", "playwright-report",
    "test-results", "__pycache__", ".pytest_cache",
    # Regenerated by `sf agent publish authoring-bundle` and gitignored; the authoring
    # bundle is the source. Excluded because these walks use rglob rather than the git
    # index, and because agentGraph/*.json is base64 despite the extension, so the JSON
    # check fails on it for anyone who has published.
    "bots", "genAiPlannerBundles",
}
MAX_TEXT_BYTES = 5_000_000
DETERMINISTIC_DATA_FIXTURES = (
    "json/harborview-los-records.json",
    "json/credit-policy-playbook.json",
)
RUNTIME_ID_SUFFIXES = {".md", ".json", ".py", ".ts", ".tsx", ".js", ".xml", ".sh", ".yml", ".yaml", ".toml", ".env", ".properties"}
SECRET_ASSIGNMENT = re.compile(
    r'''(?ix)["']?(client[_-]?secret|access[_-]?token|refresh[_-]?token|api[_-]?key|password)["']?\s*[:=]\s*["']([^"'\n]+)'''
)
PRIVATE_KEY = re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")
LIVE_BOX_HOST = re.compile(r"https?://[a-z0-9-]+\.ent\.box\.com", re.IGNORECASE)
# Experience Cloud sites answer on my.site.com, not my.salesforce.com. Only the latter
# was matched, so a run sheet naming a live site host committed cleanly.
LIVE_SALESFORCE_HOST = re.compile(
    r"https?://(?!example\.)[a-z0-9-]+(?:\.develop)?\.my\.(?:salesforce|site)\.com", re.IGNORECASE
)
LONG_NUMERIC_ID = re.compile(r"(?<![A-Za-z0-9])\d{10,}(?![A-Za-z0-9])")


class ValidationError(RuntimeError):
    """Raised when one verification row fails."""


@dataclass
class Result:
    name: str
    status: str
    seconds: float
    detail: str = ""


def run_command(command: list[str], *, cwd: Path = ROOT) -> str:
    try:
        completed = subprocess.run(command, cwd=cwd, check=True, capture_output=True, text=True)
    except (OSError, subprocess.CalledProcessError) as error:
        stdout = getattr(error, "stdout", "") or ""
        stderr = getattr(error, "stderr", "") or ""
        detail = "\n".join(part.strip() for part in (stdout, stderr) if part.strip())
        raise ValidationError(detail or str(error)) from error
    return "\n".join(part.strip() for part in (completed.stdout, completed.stderr) if part.strip())


def repository_files(root: Path = ROOT) -> list[Path]:
    if (root / ".git").exists() and shutil.which("git"):
        output = run_command(["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"], cwd=root)
        # `--cached` still lists a file deleted from the working tree but not yet staged,
        # so an uncommitted deletion used to crash every check that reads these paths.
        return [path for item in output.split("\0") if item for path in [root / item] if path.is_file()]
    return [path for path in root.rglob("*") if path.is_file() and not EXCLUDED_PARTS.intersection(path.parts)]


def secret_findings(text: str, label: str) -> list[str]:
    findings: list[str] = []
    for match in SECRET_ASSIGNMENT.finditer(text):
        value = match.group(2).strip().lower()
        if not any(marker in value for marker in ("${", "example", "placeholder", "replace", "<", "your-", "none")):
            findings.append(f"{label}: possible committed {match.group(1)}")
    if PRIVATE_KEY.search(text):
        findings.append(f"{label}: private key material")
    return findings


def check_secrets_and_runtime_ids(root: Path = ROOT) -> str:
    findings: list[str] = []
    scanned = 0
    placeholder_marker = "replace" + "-with-"
    for path in repository_files(root):
        relative = path.relative_to(root)
        if EXCLUDED_PARTS.intersection(relative.parts) or path.stat().st_size > MAX_TEXT_BYTES:
            continue
        try:
            raw = path.read_bytes()
            if b"\x00" in raw:
                continue
            text = raw.decode("utf-8")
        except UnicodeDecodeError:
            continue
        scanned += 1
        findings.extend(secret_findings(text, str(relative)))
        if LIVE_BOX_HOST.search(text):
            findings.append(f"{relative}: tenant-specific Box hostname")
        host_text = text
        if relative.as_posix() in {"README.md", "docs/demo-storyboard/index.html", "docs/demo-storyboard/standalone.html", "docs/demo-storyboard/storyboard.md", "scripts/build_demo_storyboard.py", "scripts/validate_los.py"}:
            host_text = host_text.replace("https://agentforce-box.my.site.com/loansvforcesite/login", "")
        if LIVE_SALESFORCE_HOST.search(host_text):
            findings.append(f"{relative}: org-specific Salesforce hostname")
        if placeholder_marker in text.lower() and ".example." not in path.name:
            findings.append(f"{relative}: unresolved replace-with placeholder outside an example file")
        if (
            relative.parts
            and relative.parts[0] not in {"output", "sample-data"}
            and path.suffix.lower() in RUNTIME_ID_SUFFIXES
        ):
            for line_number, line in enumerate(text.splitlines(), 1):
                if LONG_NUMERIC_ID.search(line):
                    findings.append(f"{relative}:{line_number}: possible live numeric identifier")
    if findings:
        raise ValidationError("Secrets or environment-bound values found:\n" + "\n".join(findings))
    return f"{scanned} tracked text files"


def check_json_and_schemas(root: Path = ROOT) -> str:
    try:
        from jsonschema.validators import Draft202012Validator
    except ImportError as error:
        raise ValidationError("Install Python validation dependencies: python3 -m pip install -r requirements-dev.txt") from error
    failures: list[str] = []
    count = 0
    schema_count = 0
    for path in sorted(root.rglob("*.json")):
        if EXCLUDED_PARTS.intersection(path.relative_to(root).parts) or path.name.startswith("tsconfig"):
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            count += 1
            if isinstance(data, dict) and "$schema" in data:
                Draft202012Validator.check_schema(data)
                schema_count += 1
        except Exception as error:
            failures.append(f"{path.relative_to(root)}: {error}")
    bcl_count = 0
    for path in sorted(root.rglob("*.bcl")):
        if EXCLUDED_PARTS.intersection(path.relative_to(root).parts):
            continue
        try:
            config = bcl.load_bcl(path)
            if not isinstance(config, dict):
                raise ValueError("artifact config is not an object")
            bcl_count += 1
        except Exception as error:
            failures.append(f"{path.relative_to(root)}: {error}")
    if failures:
        raise ValidationError("Invalid JSON, JSON Schema, or BCL:\n" + "\n".join(failures))
    return f"{count} JSON files, {schema_count} schemas, {bcl_count} BCL artifacts"


def check_local_links(root: Path = ROOT) -> str:
    failures: list[str] = []
    sources = [
        path for path in repository_files(root)
        if path.suffix.lower() == ".md" and not EXCLUDED_PARTS.intersection(path.relative_to(root).parts)
    ]
    for source in sources:
        for target in MARKDOWN_LINK.findall(source.read_text(encoding="utf-8")):
            if target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            destination = (source.parent / target.split("#", 1)[0]).resolve()
            if not destination.exists():
                failures.append(f"{source.relative_to(root)} -> {target}")
    if failures:
        raise ValidationError("Broken local Markdown links:\n" + "\n".join(failures))
    return f"{len(sources)} Markdown files"


def check_diagram_drift(root: Path = ROOT) -> str:
    executable = shutil.which("mmdc")
    if not executable:
        raise ValidationError("Mermaid CLI is required; install @mermaid-js/mermaid-cli so mmdc is on PATH")
    sources = sorted((root / "docs" / "diagrams").glob("*.mmd"))
    failures: list[str] = []
    with tempfile.TemporaryDirectory(prefix="los-diagrams-") as directory:
        temporary = Path(directory)
        for source in sources:
            committed = source.with_suffix(".svg")
            rendered = temporary / committed.name
            if not committed.is_file():
                failures.append(f"missing {committed.relative_to(root)}")
                continue
            run_command([executable, "-i", str(source), "-o", str(rendered), "-b", "transparent"], cwd=root)
            if rendered.read_bytes() != committed.read_bytes():
                failures.append(f"{source.relative_to(root)} -> {committed.relative_to(root)}")
    if failures:
        raise ValidationError("Mermaid/SVG drift:\n" + "\n".join(failures))
    return f"{len(sources)} source/render pairs"


def load_script(name: str, root: Path = ROOT):
    path = root / "scripts" / f"{name}.py"
    spec = importlib.util.spec_from_file_location(f"los_validation_{name}", path)
    if spec is None or spec.loader is None:
        raise ValidationError(f"Unable to import {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module



def docx_semantic_archive(path: Path) -> dict[str, bytes]:
    with zipfile.ZipFile(path) as archive:
        members: dict[str, bytes] = {}
        for name in sorted(archive.namelist()):
            content = archive.read(name)
            if name == "docProps/core.xml":
                text = content.decode("utf-8")
                text = re.sub(
                    r"(<dcterms:(?:created|modified)[^>]*>).*?(</dcterms:(?:created|modified)>)",
                    r"\1<TIMESTAMP>\2",
                    text,
                )
                content = text.encode("utf-8")
            members[name] = content
        return members


def check_generated_fixtures(root: Path = ROOT) -> str:
    try:
        import docx  # noqa: F401
        import reportlab  # noqa: F401
    except ImportError as error:
        raise ValidationError("Install Python validation dependencies: python3 -m pip install -r requirements-dev.txt") from error

    with tempfile.TemporaryDirectory(prefix="los-fixtures-") as directory:
        temporary = Path(directory)
        sample_runs: list[Path] = []
        for index in range(2):
            destination = temporary / f"sample-{index}"
            module = load_script(f"generate_sample_loan_assets", root)
            module.PDF_OUT = destination / "pdf"
            module.JSON_OUT = destination / "json"
            module.CSV_OUT = destination / "csv"
            for output in (module.PDF_OUT, module.JSON_OUT, module.CSV_OUT):
                output.mkdir(parents=True, exist_ok=True)
            module.main()
            sample_runs.append(destination)
        for relative in DETERMINISTIC_DATA_FIXTURES:
            first = sample_runs[0] / relative
            second = sample_runs[1] / relative
            committed = root / "output" / relative
            if first.read_bytes() != second.read_bytes() or first.read_bytes() != committed.read_bytes():
                raise ValidationError(f"Deterministic fixture drift: output/{relative}")
        generated_pdfs = {path.name for path in (sample_runs[0] / "pdf").glob("*.pdf")}
        committed_pdfs = {path.name for path in (root / "output" / "pdf").glob("*.pdf")}
        if generated_pdfs != committed_pdfs:
            raise ValidationError(
                "Generated loan PDFs do not match committed output/pdf: "
                f"missing={sorted(committed_pdfs - generated_pdfs)}, "
                f"unexpected={sorted(generated_pdfs - committed_pdfs)}"
            )

        docgen_runs: list[Path] = []
        for index in range(2):
            module = load_script("generate_docgen_templates", root)
            module.OUTPUT = temporary / f"docgen-{index}"
            module.main()
            docgen_runs.append(module.OUTPUT)
        expected_docx = {path.name for path in (root / "output" / "docgen").glob("*.docx")}
        generated_docx = {path.name for path in docgen_runs[0].glob("*.docx")}
        if generated_docx != expected_docx:
            raise ValidationError(
                "Doc Gen output set does not match committed output/docgen: "
                f"missing={sorted(expected_docx - generated_docx)}, "
                f"unexpected={sorted(generated_docx - expected_docx)}"
            )
        for name in expected_docx:
            first_archive = docx_semantic_archive(docgen_runs[0] / name)
            if first_archive != docx_semantic_archive(docgen_runs[1] / name) or first_archive != docx_semantic_archive(root / "output" / "docgen" / name):
                raise ValidationError(f"Doc Gen template drift: {name}")
    return (
        f"{len(committed_pdfs)} PDFs, {len(DETERMINISTIC_DATA_FIXTURES)} deterministic data fixtures, "
        f"1 trace, {len(expected_docx)} Doc Gen templates"
    )


def check_screenshot_manifest(root: Path = ROOT, *, today: date | None = None) -> str:
    today = today or datetime.now(UTC).date()
    failures: list[str] = []
    manifest_path = root / "config" / "demo" / "screenshot-manifest.bcl"
    manifest = bcl.load_bcl(manifest_path)
    entries = manifest.get("screenshots", [])
    declared = {entry.get("path") for entry in entries}
    actual = {
        path.relative_to(root).as_posix()
        for path in (root / "output" / "screenshots").rglob("*.png")
    }
    # An empty inventory is tolerated (a fresh port has captured nothing yet), but a
    # manifest that disagrees with the files on disk is not.
    if declared != actual:
        failures.append(f"screenshot manifest mismatch; missing={sorted(actual - declared)} extra={sorted(declared - actual)}")
    freshness_days = int(manifest.get("freshnessDays", 0))
    for entry in entries:
        for key in ("path", "scenario", "sourceSurface", "capturedOn", "readiness"):
            if not entry.get(key):
                failures.append(f"screenshot entry missing {key}: {entry}")
        try:
            captured = date.fromisoformat(entry["capturedOn"])
            age = (today - captured).days
            if age < 0 or age > freshness_days:
                failures.append(f"{entry['path']}: capture age {age} days exceeds 0..{freshness_days}")
        except (KeyError, ValueError) as error:
            failures.append(f"invalid capture date: {entry.get('path')}: {error}")
        if entry.get("readiness") != "real-demo":
            failures.append(f"{entry.get('path')}: readiness must be real-demo")
    if failures:
        raise ValidationError("Screenshot manifest failures:\n" + "\n".join(failures))
    return f"{len(entries)} current real screenshots" if entries else "0 screenshots (capture pending)"


def check_reset_and_idempotency_rules(root: Path = ROOT) -> str:
    operator = bcl.load_bcl(root / "config" / "operator" / "operator-workflow.bcl")
    connectors = bcl.load_bcl(root / "config" / "box" / "https-connectors.bcl")
    operator_text = json.dumps(operator).lower()
    connector_text = json.dumps(connectors).lower()
    manual_text = (root / "docs" / "SETUP.md").read_text(encoding="utf-8").lower()
    required = {
        "operator duplicate check": "duplicate" in operator_text,
        "operator reset check": "reset" in operator_text,
        "connector idempotency key": "idempotencykey" in connector_text,
        "manual reset tasks": "reset" in manual_text,
    }
    missing = [name for name, present in required.items() if not present]
    if missing:
        raise ValidationError("Missing reset/idempotency rules: " + ", ".join(missing))
    return "portable retry, duplicate, confirmation, and reset rules"


def check_live_receipts(root: Path = ROOT, *, required: bool) -> str:
    path = root / "config" / "runtime" / "validation-receipts.json"
    if not path.is_file():
        if required:
            raise ValidationError("Presenter-ready validation requires config/runtime/validation-receipts.json")
        return "SKIP:repository mode; live environment receipts are not required"
    receipt_text = path.read_text(encoding="utf-8")
    receipt_secrets = secret_findings(receipt_text, str(path.relative_to(root)))
    if receipt_secrets:
        raise ValidationError("Secrets found in live receipts:\n" + "\n".join(receipt_secrets))
    data = json.loads(receipt_text)
    receipts = data.get("receipts", [])
    freshness_days = int(data.get("freshnessDays", 30))
    failures: list[str] = []
    placeholder_marker = "replace" + "-with-"
    for receipt in receipts:
        platform = receipt.get("platform", "unknown")
        for key in ("environment", "validatedAt", "actionMode", "businessKey", "status", "evidence", "cleanupOwner"):
            value = receipt.get(key)
            if not value or placeholder_marker in str(value).lower():
                failures.append(f"{platform}: missing or placeholder {key}")
        try:
            validated = datetime.fromisoformat(str(receipt["validatedAt"]).replace("Z", "+00:00"))
            age = (datetime.now(UTC) - validated.astimezone(UTC)).days
            if age < 0 or age > freshness_days:
                failures.append(f"{platform}: receipt age {age} days exceeds 0..{freshness_days}")
        except (KeyError, ValueError) as error:
            failures.append(f"{platform}: invalid validatedAt: {error}")
    if failures:
        raise ValidationError("Live receipt validation failed:\n" + "\n".join(failures))
    platforms = {
        receipt.get("platform")
        for receipt in receipts
        if receipt.get("status") == "passed" and receipt.get("actionMode") == "live"
    }
    expected = {"Box", "Salesforce"}
    if platforms != expected:
        raise ValidationError(f"Live receipt coverage is incomplete: expected={sorted(expected)} actual={sorted(platforms)}")
    return "Box and Salesforce receipts"


def check_presenter_output(root: Path = ROOT) -> str:
    guides = load_script("build_scenario_guides", root)
    portal = load_script("build_presenter_portal", root)
    with tempfile.TemporaryDirectory(prefix="los-presenters-") as directory:
        guides.OUTPUT = Path(directory)
        for scenario in guides.SCENARIOS:
            guides.build_scenario(scenario)
        portal.build_landing(Path(directory) / "index.html")
        portal.build_combined(Path(directory), Path(directory) / "06-complete-presenter-edition.html")
        for generated in Path(directory).glob("*.html"):
            committed = root / "output" / "html" / generated.name
            if not committed.exists() or generated.read_bytes() != committed.read_bytes():
                raise ValidationError(f"Presenter drift: {committed.relative_to(root)}")
    return "3 canonical chapters, landing page and self-contained edition"


def check_react_script(script: str, root: Path = ROOT) -> str:
    workspace = root / REACT.relative_to(ROOT)
    if not (workspace / "node_modules").is_dir():
        raise ValidationError(f"{workspace.relative_to(root)} is missing node_modules; run npm ci")
    package = json.loads((workspace / "package.json").read_text(encoding="utf-8"))
    if script not in package.get("scripts", {}):
        raise ValidationError(f"React workspace does not define npm run {script}")
    if script == "test":
        command = ["npm", "test", "--", "--run"]
    elif script == "build":
        command = ["npm", "run", "build", "--", "--mode", "standalone"]
    else:
        command = ["npm", "run", script]
    run_command(command, cwd=workspace)
    return workspace.relative_to(root).as_posix()


CARD = ROOT / "connectors" / "demo-setup-card"


def check_card_script(script: str, root: Path = ROOT) -> str:
    """Build or test the Demo Setup card connector (an MCP Apps server) when its node_modules exist."""
    workspace = root / CARD.relative_to(ROOT)
    if not (workspace / "node_modules").is_dir():
        raise ValidationError(f"{workspace.relative_to(root)} is missing node_modules; run npm ci")
    package = json.loads((workspace / "package.json").read_text(encoding="utf-8"))
    if script not in package.get("scripts", {}):
        raise ValidationError(f"Demo Setup card workspace does not define npm run {script}")
    run_command(["npm", "run", script], cwd=workspace)
    return workspace.relative_to(root).as_posix()


def execute(name: str, action: Callable[[], str]) -> Result:
    start = time.monotonic()
    try:
        detail = action()
        if detail.startswith("SKIP:"):
            return Result(name, "SKIP", time.monotonic() - start, detail.removeprefix("SKIP:"))
        return Result(name, "PASS", time.monotonic() - start, detail)
    except Exception as error:  # keep the full matrix visible after a failure
        return Result(name, "FAIL", time.monotonic() - start, str(error))


def check_soql_field_permissions(root: Path = ROOT) -> str:
    """Check the authenticated projection without exposing signing links to guests.

    Guests must be rejected before the reader runs. Only authenticated borrowers
    need projection field grants; new internal receipt fields are not in this list.
    """
    service = root / "los-salesforce-project/force-app/main/default/classes/LosLoanListService.cls"
    if not service.exists():
        raise ValidationError(f"missing {service.relative_to(root)}")

    source = service.read_text()
    guard_start = source.find("if (UserInfo.getUserType() == 'Guest')")
    reader = source.find("new LoanReader().read()")
    guard = source[guard_start:reader] if guard_start >= 0 and reader > guard_start else ""
    if "response.statusCode = 401" not in guard or "return;" not in guard:
        raise ValidationError("Guest rejection must precede the loan reader")

    match = re.search(r"SELECT\s+(.*?)\s+FROM\s+LOS_Loan__c", service.read_text(), re.IGNORECASE | re.DOTALL)
    if not match:
        raise ValidationError("could not find the LOS_Loan__c projection in LosLoanListService")
    selected = {
        field.strip()
        for field in match.group(1).split(",")
        if field.strip().endswith("__c")
    }
    if not selected:
        raise ValidationError("the LOS_Loan__c projection parsed as empty; the check would prove nothing")

    findings: list[str] = []
    permissions = root / "los-salesforce-project/force-app/main/default/permissionsets"
    for name in ("LOS_Borrower_Portal",):
        path = permissions / f"{name}.permissionset-meta.xml"
        if not path.exists():
            findings.append(f"{name}: permission set not found")
            continue
        granted = set(re.findall(r"<field>LOS_Loan__c\.([A-Za-z0-9_]+)</field>", path.read_text()))
        for field in sorted(selected - granted):
            findings.append(f"{name}: does not grant {field}, which the REST projection selects")

    if findings:
        raise ValidationError(
            "SOQL projection and permission sets disagree:\n" + "\n".join(findings)
        )
    return f"{len(selected)} projected fields granted for authenticated borrowers"


def validate(*, skip_react: bool, skip_playwright: bool, presenter_ready: bool, root: Path = ROOT) -> list[Result]:
    rows: list[tuple[str, Callable[[], str]]] = [
        ("secrets + runtime IDs", lambda: check_secrets_and_runtime_ids(root)),
        ("JSON + schemas", lambda: check_json_and_schemas(root)),
        ("local Markdown links", lambda: check_local_links(root)),
        ("Mermaid/SVG drift", lambda: check_diagram_drift(root)),
        ("Python tests", lambda: run_command([sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"], cwd=root)),
        ("generated fixtures", lambda: check_generated_fixtures(root)),
        ("generated presenters", lambda: check_presenter_output(root)),
        ("screenshot manifest", lambda: check_screenshot_manifest(root)),
        ("reset + idempotency", lambda: check_reset_and_idempotency_rules(root)),
        ("SOQL field permissions", lambda: check_soql_field_permissions(root)),
    ]
    if not skip_react:
        rows.extend([
            ("React unit tests", lambda: check_react_script("test", root)),
            ("React lint", lambda: check_react_script("lint", root)),
            ("React build", lambda: check_react_script("build", root)),
            ("Demo Setup card tests", lambda: check_card_script("test", root)),
            ("Demo Setup card build", lambda: check_card_script("build", root)),
        ])
        if not skip_playwright:
            rows.append(("Playwright", lambda: check_react_script("test:e2e", root)))
    rows.append(("live validation receipts", lambda: check_live_receipts(root, required=presenter_ready)))
    return [execute(name, action) for name, action in rows]


def print_matrix(results: list[Result]) -> None:
    width = max(len(item.name) for item in results)
    for item in results:
        first_line = item.detail.splitlines()[0] if item.detail else ""
        print(f"{item.status:<4}  {item.name:<{width}}  {item.seconds:>6.2f}s  {first_line}")
    passed = sum(item.status == "PASS" for item in results)
    failed = sum(item.status == "FAIL" for item in results)
    skipped = sum(item.status == "SKIP" for item in results)
    print(f"\nSummary: {passed} passed, {failed} failed, {skipped} skipped")
    for item in results:
        if item.status == "FAIL":
            print(f"\n[{item.name}]\n{item.detail}")


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--presenter-ready", action="store_true", help="Require current live validation receipts for every platform")
    result.add_argument("--skip-react", action="store_true", help="Skip the Node checks: React unit, lint, build, Playwright, and the Demo Setup card")
    result.add_argument("--skip-playwright", action="store_true", help="Run React unit, lint, and build without browser E2E")
    result.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    return result


def main() -> int:
    args = parser().parse_args()
    results = validate(
        skip_react=args.skip_react,
        skip_playwright=args.skip_playwright,
        presenter_ready=args.presenter_ready,
        root=args.root.resolve(),
    )
    print_matrix(results)
    return 1 if any(item.status == "FAIL" for item in results) else 0


if __name__ == "__main__":
    raise SystemExit(main())
